version: "3.8"

services:
  eureka-server:
    container_name: apiGateway
    ports:
      - "8080:8080"
    build: ./
    environment:
      - spring.application.name=api-gateway
      - eureka.client.service-url.defaultZone=http://eurekaServer:8761/eureka/
      - logging.level.root=INFO
      - logging.level.org.springframework.cloud.gateway.route.RouteDefinitionLocator=INFO
      - logging.level.org.springframework.cloud.gateway=TRACE
      - spring.cloud.gateway.discovery.locator.enabled=true
      - spring.cloud.gateway.discovery.locator.lower-case-service-id=true
      - spring.cloud.gateway.routes[0].id=user-service
      - spring.cloud.gateway.routes[0].uri=lb://user-service
      - spring.cloud.gateway.routes[0].predicates[0]=Path=/registration, /login, /confirm-email, /resend-confirmation-email, /refresh-token, /validate-auth-token, /users/**
      - spring.cloud.gateway.routes[1].id=backoffice-service
      - spring.cloud.gateway.routes[1].uri=lb://backoffice-service
      - spring.cloud.gateway.routes[1].predicates[0]=Path=/manager/**, /user/**
      - spring.cloud.gateway.routes[2].id=car-service
      - spring.cloud.gateway.routes[2].uri=lb://car-service
      - spring.cloud.gateway.routes[2].predicates[0]=Path=/cars/**
      - spring.cloud.gateway.routes[3].id=trip-service
      - spring.cloud.gateway.routes[3].uri=lb://trip-service
      - spring.cloud.gateway.routes[3].predicates[0]=Path=/trip/**
